# HopSkipJump Attack on All Models

This notebook assumes you already have the following helper functions available
in the environment (import them from your own modules before running this):

- `run_logreg("CSVs/newDataset.csv")`
- `run_neuralnet("CSVs/newDataset.csv")`
- `run_randomforest("CSVs/newDataset.csv")`
- `run_svm("CSVs/newDataset.csv")`
- `run_xgboost("CSVs/newDataset.csv")`

Each function is expected to return a tuple:

```python
(model, X_test, y_test)
```

where:
- `model` is a trained classifier (pipeline or estimator)
- `X_test` is the test feature matrix (pandas DataFrame or numpy array)
- `y_test` is the corresponding true labels

The notebook then applies the HopSkipJump attack from ART to each model and
reports clean vs adversarial accuracy.

In [6]:
# Imports

import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score

# Adversarial Robustness Toolbox (ART)
from art.estimators.classification import SklearnClassifier
from art.attacks.evasion import HopSkipJump

# IMPORTANT:
# Make sure you import your run_* helpers here, for example:
#
from MachineLearning.LogReg.LogisticRegression_ML import run_best_model as run_logreg
from MachineLearning.NeuralNetworks.NeuralNet_ML import run_best_model as run_neuralnet
from MachineLearning.RandomForest.RandomForest_ML import run_best_model as run_randomforest
from MachineLearning.SVM.SVM_ML import run_best_model as run_svm
from MachineLearning.XGBoost.XGBoost_ML import run_best_model as run_xgboost
#
# or import your wrapper functions that already call those.


import warnings

warnings.filterwarnings(
    "ignore",
    message="X does not have valid feature names, but StandardScaler was fitted with feature names",
    category=UserWarning,
)

In [7]:
# Set seed for reproducibility

SEED = 42
np.random.seed(SEED)

In [8]:
# Run all models on the same dataset path
# Assumes each function returns (model, X_test, y_test)

DATA_PATH = "CSVs/newDataset.csv"

model_runs = {}

print("Running Logistic Regression...")
logreg_model, logreg_X_test, logreg_y_test = run_logreg(DATA_PATH)
model_runs["LogisticRegression"] = (logreg_model, logreg_X_test, logreg_y_test)

print("Running Neural Net...")
nn_model, nn_X_test, nn_y_test = run_neuralnet(DATA_PATH)
model_runs["NeuralNet"] = (nn_model, nn_X_test, nn_y_test)

print("Running Random Forest...")
rf_model, rf_X_test, rf_y_test = run_randomforest(DATA_PATH)
model_runs["RandomForest"] = (rf_model, rf_X_test, rf_y_test)

print("Running SVM...")
svm_model, svm_X_test, svm_y_test = run_svm(DATA_PATH)
model_runs["SVM"] = (svm_model, svm_X_test, svm_y_test)

print("Running XGBoost...")
xgb_model, xgb_X_test, xgb_y_test = run_xgboost(DATA_PATH)
model_runs["XGBoost"] = (xgb_model, xgb_X_test, xgb_y_test)

print("\nSummary of collected models:")
for name, (model, X_test, y_test) in model_runs.items():
    print(f" - {name}: model={type(model)}, X_test shape={getattr(X_test, 'shape', None)}")

Running Logistic Regression...
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.936)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.96      0.94      0.95      1352
           1       0.77      0.83      0.80       347

    accuracy                           0.92      1699
   macro avg       0.87      0.89      0.87      1699
weighted avg       0.92      0.92      0.92      1699


Confusion Matrix:
         Pred 0  Pred 1
True 0    1268      84
True 1      58     289

AUC: 0.936

=== All results and summaries saved successfully ===
Running Neural Net...
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.962)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1352
           1       0.87      0.86      0.87       347

    accuracy                           0.95      1699
   macro avg       0.92      0.91      0.92      1699
weighted avg       0.95      0.95      0.95      1699


Confusion Matrix:
         Pred 0  Pred 1
True 0    1309      43
True 1      49     298

AUC: 0.962

=== All results and summaries saved successfully ===
Running Random Forest...

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.972)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1352
           1       0.93      0.80      0.86       347

    accuracy                           0.95      1699
   macro avg       0.94      0.89      0.91      1699
weighted avg       0.94      0.95      0.94      1699


Confusion Matrix:
         Pred 0  Pred 1
True 0    1330      22
True 1      71     276

AUC: 0.972

=== All results and summaries saved successfully ===
Running SVM...

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.934)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      1520
           1       0.94      0.70      0.80       391

    accuracy                           0.93      1911
   macro avg       0.93      0.84      0.88      1911
weighted avg       0.93      0.93      0.93      1911


Confusion Matrix:
         Pred 0  Pred 1
True 0    1503      17
True 1     117     274

AUC: 0.934

=== All results and summaries saved successfully ===
Running XGBoost...

Saved XGBoost last run results to Results/XGBoostResults\results_xgboost.csv
Saved ROC data to Results/XGBoostResults\roc_xgboost_clean.csv (AUC = 0.964)
Saved summary (AUC + Confusion Matrix) to Results/XGBoostResults\xgboost_summary.csv

=== XGBoost Test Set Report ===
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1352
           1       0.91      0.80      0.85       347

    accuracy                           0.94      1699
   macro avg       0.93      0.89      0.91      1699
weighted avg       0.94      0.94      0.94      1699


Confusion Matrix:
         Pred 0  Pred 1
True 0    1325      27
True 1      69     278

AUC: 0.964

=== All results and summaries saved successfully ===

Summary of collected models:
 - LogisticRegression: model=<class 'sklearn.pipeline.Pipeline'>, X_test shape=(1699, 22)
 - NeuralNet: model=<class 'sklearn.pipeline.Pipeline'>, X_test shape=(1699, 22)
 - RandomForest: model=<class 'sklearn.pipeline.Pipeline'>, X_test shape=(1699, 22)
 - SVM: model=<class 'sklearn.pipeline.Pipeline'>, X_test shape=(1911, 22)
 - XGBoost: model=<class 'xgboost.sklearn.XGBClassifier'>, X_test shape=(1699, 22)

C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\training.py:183: UserWarning: [18:33:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [16]:
# HopSkipJump attack on each model

import xgboost as xgb
from art.estimators.classification import SklearnClassifier, XGBoostClassifier
from art.attacks.evasion import HopSkipJump
import numpy as np
import pandas as pd

hsj_kwargs = dict(
    max_iter=20,
    max_eval=10000,
    init_eval=100,
    init_size=10,
    targeted=False,
    norm=2,
)

results_hsj = {}

# Limit samples per model (keep or change to match your notebook)
MAX_SAMPLES = 200


def make_art_classifier(model, X, y, clip_values=(0, 1)):
    """
    Wraps the model in the correct ART classifier.
    Uses XGBoostClassifier for XGBoost models, SklearnClassifier otherwise.
    """
    # XGBoost branch
    if isinstance(model, xgb.XGBClassifier):
        print("Wrapping model with ART XGBoostClassifier for HopSkipJump")
        nb_classes = int(len(np.unique(y)))
        nb_features = int(X.shape[1])
        return XGBoostClassifier(
            model=model,
            nb_features=nb_features,
            nb_classes=nb_classes,
            clip_values=clip_values,
        )

    # Default: sklearn-compatible models
    print("Wrapping model with ART SklearnClassifier for HopSkipJump")
    return SklearnClassifier(model=model, clip_values=clip_values)


for name, (model, X_test, y_test) in model_runs.items():
    print("\n=== HopSkipJump attack on model:", name, "===")

    # Convert data to numpy
    if hasattr(X_test, "to_numpy"):
        X_all = X_test.to_numpy().astype(np.float32)
    else:
        X_all = np.asarray(X_test, dtype=np.float32)

    if hasattr(y_test, "to_numpy"):
        y_all = y_test.to_numpy()
    else:
        y_all = np.asarray(y_test)

    # Optional: limit number of samples
    n_total = len(X_all)
    n = min(MAX_SAMPLES, n_total)
    X = X_all[:n]
    y = y_all[:n]

    # Ensure labels are integer-encoded 1D
    if isinstance(y, pd.Series):
        y = y.to_numpy()
    y_int = y.astype(int).reshape(-1)

    n = X.shape[0]
    print(f"Using {n} samples for HopSkipJump on {name}")

    # Build ART classifier (XGBoost or Sklearn)
    art_classifier = make_art_classifier(model, X, y_int, clip_values=(0, 1))

    # Create HopSkipJump instance
    hsj_attack = HopSkipJump(classifier=art_classifier, **hsj_kwargs)

    clean_correct = 0
    adv_correct = 0

    for i in range(n):
        xi = X[i:i+1]
        yi = y_int[i:i+1]

        # Prediction on clean input
        pred_clean = np.argmax(art_classifier.predict(xi), axis=1)

        # Generate adversarial example (HopSkipJump is decision-based)
        x_adv = hsj_attack.generate(x=xi, y=yi)

        # Prediction on adversarial input
        pred_adv = np.argmax(art_classifier.predict(x_adv), axis=1)

        # Compare scalars explicitly
        clean_correct += int(pred_clean[0] == yi[0])
        adv_correct   += int(pred_adv[0]   == yi[0])

    clean_acc = clean_correct / n
    adv_acc = adv_correct / n

    print(f"{name} clean acc (HSJ): {clean_acc:.4f}")
    print(f"{name} adv   acc (HSJ): {adv_acc:.4f}")

    results_hsj[name] = dict(clean_acc=float(clean_acc), adv_acc=float(adv_acc))

hsj_results_df = pd.DataFrame(results_hsj).T
hsj_results_df

=== HopSkipJump attack on model: LogisticRegression ===
Using 200 samples for HopSkipJump on LogisticRegression
Wrapping model with ART SklearnClassifier for HopSkipJump

HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 496.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 501.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.95it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 498.37it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 493.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 498.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 506.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 498.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 494.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 492.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 317.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 336.06it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 397.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  7.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 337.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 209.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 226.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 239.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.94it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.22it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.95it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.07it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 437.13it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 548.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 399.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.06it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 398.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.89it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.79it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 397.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.22it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 330.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]

LogisticRegression clean acc (HSJ): 0.9100
LogisticRegression adv   acc (HSJ): 0.6750

=== HopSkipJump attack on model: NeuralNet ===
Using 200 samples for HopSkipJump on NeuralNet
Wrapping model with ART SklearnClassifier for HopSkipJump

HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 166.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 336.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 336.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 492.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.07it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 335.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 329.53it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 395.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 330.83it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.83it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.64it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 511.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 492.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 330.21it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 331.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.91it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 497.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 496.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 166.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 335.79it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.94it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.06it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.91it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 497.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.06it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 90.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 142.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 95.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 142.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 221.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 261.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.13it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 328.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 244.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 495.55it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 285.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 221.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 232.91it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.07it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 244.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.48it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 391.95it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.88it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 397.83it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.79it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 330.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 222.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 324.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 336.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.82it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 221.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 166.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 167.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.06it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 251.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 330.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 233.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 221.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.88it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 403.53it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 501.29it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 285.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 285.21it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 285.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.29it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 499.92it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 331.72it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.59it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 332.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 405.48it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.40it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 335.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 282.90it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.61it/s]

NeuralNet clean acc (HSJ): 0.9600
NeuralNet adv   acc (HSJ): 0.7350

=== HopSkipJump attack on model: RandomForest ===
Using 200 samples for HopSkipJump on RandomForest
Wrapping model with ART SklearnClassifier for HopSkipJump

HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.41it/s]
HopSkipJump: 100%|██████████| 1/1 [00:07<00:00,  7.06s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  7.00s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.85s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.66s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.97s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.92s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  2.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.71s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.73s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.57s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.51s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.57s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.55it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.78s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.66s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.61s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.92s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.67s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.79s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.63s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.62s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.80s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.49s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.44s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.43s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.48s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.41s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.38s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.40s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.65s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.40s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.59s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.68s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.52s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.47s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.37s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.62s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.99s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:07<00:00,  7.07s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.69s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.30s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.35s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.51s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.51s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.26s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.63s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.38s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.60s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.42s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  7.00s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.35s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.47s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.43s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.66s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.29s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.41s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.73s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.36s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.22s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.51s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.28s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.26s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.36s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.58s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.76s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.31s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.79s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.66s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.55s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.54s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.59s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.59s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.52s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.27s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.52s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.37s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.68s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.57s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.46s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.46s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.43s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.47s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.39s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.64it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.55s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.44s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.77s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.61it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.75s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.57s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.64s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.63s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.89s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.71s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.68s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.90s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.53s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.71s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.34s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.57s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.36s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.45s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.67s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.70s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.83s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.59s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.95s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.58s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.64s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.46s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.47s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.46s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.27s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  2.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.65s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.37s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.58s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.73s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.72s/it]
HopSkipJump: 100%|██████████| 1/1 [00:06<00:00,  6.81s/it]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  3.70it/s]

RandomForest clean acc (HSJ): 0.9600
RandomForest adv   acc (HSJ): 0.3100

=== HopSkipJump attack on model: SVM ===
Using 200 samples for HopSkipJump on SVM
Wrapping model with ART SklearnClassifier for HopSkipJump

HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.04it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.79it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 500.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.88it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 366.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 492.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.19it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.72it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.70it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.79it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 270.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.37it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 319.10it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.89it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.88it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.21it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.08it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.94it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 346.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.42it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 496.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.82it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.59it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.78it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.57it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 344.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 392.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 505.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 327.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.42it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 498.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 399.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.50it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.45it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.59it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 475.28it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.37it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.60it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.16it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.08it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.21it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.51it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.85it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.68it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 495.55it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.73it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.67it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 15.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 16.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 514.07it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.31it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.83it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 14.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.65it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.86it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 493.74it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.09it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 495.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.21it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.27it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.55it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.39it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.66it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.87it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 490.22it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.44it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.84it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 17.53it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 496.19it/s]

SVM clean acc (HSJ): 0.9000
SVM adv   acc (HSJ): 0.1700

=== HopSkipJump attack on model: XGBoost ===
Using 200 samples for HopSkipJump on XGBoost
Wrapping model with ART XGBoostClassifier for HopSkipJump

HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.47it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 199.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.01it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.97it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.26it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.77it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.22it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.58it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.03it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.75it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00,  9.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.25it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.38it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.49it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.69it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.15it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.36it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 249.99it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.81it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.17it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 333.33it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.56it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 250.00it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 10.93it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.43it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.30it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.11it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 285.46it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 200.02it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.24it/s]
HopSkipJump: 100%|██████████| 1/1 [00:00<00:00, 11.05it/s]

XGBoost clean acc (HSJ): 0.9650
XGBoost adv   acc (HSJ): 0.2150

                    clean_acc  adv_acc
LogisticRegression      0.910    0.675
NeuralNet               0.960    0.735
RandomForest            0.960    0.310
SVM                     0.900    0.170
XGBoost                 0.965    0.215

In [17]:
# ================================================================
#   SKLEARN METRICS SUMMARY FOR CLEAN + HOPSKIPJUMP PERFORMANCE
# ================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
import numpy as np
import pandas as pd

# ----------------------------------------------------------------
# Ensure we have model_runs; rebuild if necessary
# ----------------------------------------------------------------
if "model_runs" not in globals():
    print("model_runs not found, rebuilding using run_* helpers...")

    DATA_PATH = "CSVs/newDataset.csv"
    model_runs = {}

    print("Running Logistic Regression...")
    logreg_model, logreg_X_test, logreg_y_test = run_logreg(DATA_PATH)
    model_runs["LogisticRegression"] = (logreg_model, logreg_X_test, logreg_y_test)

    print("Running Neural Net...")
    nn_model, nn_X_test, nn_y_test = run_neuralnet(DATA_PATH)
    model_runs["NeuralNet"] = (nn_model, nn_X_test, nn_y_test)

    print("Running Random Forest...")
    rf_model, rf_X_test, rf_y_test = run_randomforest(DATA_PATH)
    model_runs["RandomForest"] = (rf_model, rf_X_test, rf_y_test)

    print("Running SVM...")
    svm_model, svm_X_test, svm_y_test = run_svm(DATA_PATH)
    model_runs["SVM"] = (svm_model, svm_X_test, svm_y_test)

    print("Running XGBoost...")
    xgb_model, xgb_X_test, xgb_y_test = run_xgboost(DATA_PATH)
    model_runs["XGBoost"] = (xgb_model, xgb_X_test, xgb_y_test)

hsj_summary_rows = []

print("\n\n===================== HOPSKIPJUMP METRICS SUMMARY =====================\n")

for name, (model, X_test, y_test) in model_runs.items():

    print("\n\n################################################################")
    print("MODEL:", name)
    print("################################################################")

    # Convert labels
    if hasattr(y_test, "to_numpy"):
        y_true = y_test.to_numpy()
    else:
        y_true = np.asarray(y_test)

    # Clean predictions from the trained model
    y_pred = model.predict(X_test)

    # Basic clean metrics
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average="weighted", zero_division=0)
    rec  = recall_score(y_true, y_pred, average="weighted", zero_division=0)
    f1   = f1_score(y_true, y_pred, average="weighted", zero_division=0)

    print("\nCLEAN PERFORMANCE")
    print("----------------------------")
    print("Accuracy:", acc)
    print("Precision:", prec)
    print("Recall:", rec)
    print("F1 Score:", f1)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, zero_division=0))

    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))

    # Row for summary table
    row = {
        "Model": name,
        "Clean Accuracy": acc,
        "Clean F1": f1
    }

    # ============================
    #   HOPSKIPJUMP RESULTS
    # ============================
    if "results_hsj" in globals() and name in results_hsj:
        hsj_clean = results_hsj[name]["clean_acc"]
        hsj_adv   = results_hsj[name]["adv_acc"]
        hsj_drop  = hsj_clean - hsj_adv

        print("\nHOPSKIPJUMP ADVERSARIAL RESULTS")
        print("----------------------------")
        print("Clean Accuracy (HSJ dict):", hsj_clean)
        print("Adv Accuracy   (HSJ):     ", hsj_adv)
        print("Accuracy Drop:", hsj_drop)

        row["HSJ Adv Accuracy"] = hsj_adv
        row["HSJ Drop"] = hsj_drop
    else:
        print("\nNo HSJ results recorded for this model in results_hsj.")

    hsj_summary_rows.append(row)

# Create dataframe summary
hsj_metrics_summary_df = pd.DataFrame(hsj_summary_rows)
print("\n\n===================== HSJ SUMMARY DATAFRAME =====================\n")
display(hsj_metrics_summary_df)

hsj_metrics_summary_df

===================== HOPSKIPJUMP METRICS SUMMARY =====================



################################################################
MODEL: LogisticRegression
################################################################

CLEAN PERFORMANCE
----------------------------
Accuracy: 0.9164214243672749
Precision: 0.9191983360683207
Recall: 0.9164214243672749
F1 Score: 0.9175247607419302

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95      1352
           1       0.77      0.83      0.80       347

    accuracy                           0.92      1699
   macro avg       0.87      0.89      0.87      1699
weighted avg       0.92      0.92      0.92      1699

Confusion Matrix:
[[1268   84]
 [  58  289]]

HOPSKIPJUMP ADVERSARIAL RESULTS
----------------------------
Clean Accuracy (HSJ dict): 0.91
Adv Accuracy   (HSJ):      0.675
Accuracy Drop: 0.235


################################################################
MODEL: NeuralNet
################################################################

CLEAN PERFORMANCE
----------------------------
Accuracy: 0.9458505002942907
Precision: 0.945532605417829
Recall: 0.9458505002942907
F1 Score: 0.9456743273853752

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1352
           1       0.87      0.86      0.87       347

    accuracy                           0.95      1699
   macro avg       0.92      0.91      0.92      1699
weighted avg       0.95      0.95      0.95      1699

Confusion Matrix:
[[1309   43]
 [  49  298]]

HOPSKIPJUMP ADVERSARIAL RESULTS
----------------------------
Clean Accuracy (HSJ dict): 0.96
Adv Accuracy   (HSJ):      0.735
Accuracy Drop: 0.22499999999999998


################################################################
MODEL: RandomForest
################################################################

CLEAN PERFORMANCE
----------------------------
Accuracy: 0.9452619187757504
Precision: 0.9445943358460992
Recall: 0.9452619187757504
F1 Score: 0.9436698554633343

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1352
           1       0.93      0.80      0.86       347

    accuracy                           0.95      1699
   macro avg       0.94      0.89      0.91      1699
weighted avg       0.94      0.95      0.94      1699

Confusion Matrix:
[[1330   22]
 [  71  276]]

HOPSKIPJUMP ADVERSARIAL RESULTS
----------------------------
Clean Accuracy (HSJ dict): 0.96
Adv Accuracy   (HSJ):      0.31
Accuracy Drop: 0.6499999999999999


################################################################
MODEL: SVM
################################################################

CLEAN PERFORMANCE
----------------------------
Accuracy: 0.9298796441653584
Precision: 0.9306019350201972
Recall: 0.9298796441653584
F1 Score: 0.9258554217901425

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      1520
           1       0.94      0.70      0.80       391

    accuracy                           0.93      1911
   macro avg       0.93      0.84      0.88      1911
weighted avg       0.93      0.93      0.93      1911

Confusion Matrix:
[[1503   17]
 [ 117  274]]

HOPSKIPJUMP ADVERSARIAL RESULTS
----------------------------
Clean Accuracy (HSJ dict): 0.9
Adv Accuracy   (HSJ):      0.17
Accuracy Drop: 0.73


################################################################
MODEL: XGBoost
################################################################

CLEAN PERFORMANCE
----------------------------
Accuracy: 0.9434961742201294
Precision: 0.9425314166131492
Recall: 0.9434961742201294
F1 Score: 0.9421083780085491

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1352
           1       0.91      0.80      0.85       347

    accuracy                           0.94      1699
   macro avg       0.93      0.89      0.91      1699
weighted avg       0.94      0.94      0.94      1699

Confusion Matrix:
[[1325   27]
 [  69  278]]

HOPSKIPJUMP ADVERSARIAL RESULTS
----------------------------
Clean Accuracy (HSJ dict): 0.965
Adv Accuracy   (HSJ):      0.215
Accuracy Drop: 0.75


===================== HSJ SUMMARY DATAFRAME =====================

                Model  Clean Accuracy  Clean F1  HSJ Adv Accuracy  HSJ Drop
0  LogisticRegression        0.916421  0.917525             0.675     0.235
1           NeuralNet        0.945851  0.945674             0.735     0.225
2        RandomForest        0.945262  0.943670             0.310     0.650
3                 SVM        0.929880  0.925855             0.170     0.730
4             XGBoost        0.943496  0.942108             0.215     0.750

                Model  Clean Accuracy  Clean F1  HSJ Adv Accuracy  HSJ Drop
0  LogisticRegression        0.916421  0.917525             0.675     0.235
1           NeuralNet        0.945851  0.945674             0.735     0.225
2        RandomForest        0.945262  0.943670             0.310     0.650
3                 SVM        0.929880  0.925855             0.170     0.730
4             XGBoost        0.943496  0.942108             0.215     0.750

In [18]:
from art.attacks.evasion import HopSkipJump
from art.estimators.classification import SklearnClassifier
from sklearn.metrics import accuracy_score
import numpy as np

def evaluate_robustness_hsj(model, X_test, y_test, max_samples=100, hsj_kwargs=None):
    if hsj_kwargs is None:
        hsj_kwargs = dict(
            max_iter=20,
            max_eval=10000,
            init_eval=100,
            init_size=10,
            targeted=False,
            norm=2,
        )

    # to numpy
    X = X_test.to_numpy().astype(np.float32) if hasattr(X_test, "to_numpy") else np.asarray(X_test, dtype=np.float32)
    y_raw = y_test.to_numpy() if hasattr(y_test, "to_numpy") else np.asarray(y_test)

    # encode to 0..K-1 for ART
    classes, y_int = np.unique(y_raw, return_inverse=True)

    n = min(max_samples, len(X))
    X = X[:n]
    y = y_int[:n]

    clip_values = (float(X.min()), float(X.max()))
    art_clf = SklearnClassifier(model=model, clip_values=clip_values)

    # clean accuracy on this subset
    preds_clean = np.argmax(art_clf.predict(X), axis=1)
    clean_acc = accuracy_score(y, preds_clean)

    # run HSJ
    hsj = HopSkipJump(classifier=art_clf, **hsj_kwargs)
    X_adv = hsj.generate(x=X, y=y)

    preds_adv = np.argmax(art_clf.predict(X_adv), axis=1)
    adv_acc = accuracy_score(y, preds_adv)

    return {
        "clean_acc": clean_acc,
        "adv_acc": adv_acc,
        "acc_drop": clean_acc - adv_acc,
        "num_samples": n,
    }

In [19]:
results = []
for name, (model, X_test, y_test) in model_runs.items():
    # optionally skip XGB if HSJ is unstable
    if "xgb" in name.lower():
        print(f"Skipping {name} (XGBoost) for HSJ robustness evaluation.")
        continue

    print(f"\nEvaluating robustness for {name}")
    res = evaluate_robustness_hsj(model, X_test, y_test, max_samples=100)
    res["Model"] = name
    print(res)
    results.append(res)

robust_df = pd.DataFrame(results)
display(robust_df)

Evaluating robustness for LogisticRegression

HopSkipJump: 100%|██████████| 100/100 [00:01<00:00, 56.59it/s]

{'clean_acc': 0.93, 'adv_acc': 0.69, 'acc_drop': 0.2400000000000001, 'num_samples': 100, 'Model': 'LogisticRegression'}

Evaluating robustness for NeuralNet

HopSkipJump: 100%|██████████| 100/100 [00:02<00:00, 49.79it/s]

{'clean_acc': 0.96, 'adv_acc': 0.71, 'acc_drop': 0.25, 'num_samples': 100, 'Model': 'NeuralNet'}

Evaluating robustness for RandomForest

HopSkipJump: 100%|██████████| 100/100 [08:38<00:00,  5.18s/it]

{'clean_acc': 0.96, 'adv_acc': 0.2, 'acc_drop': 0.76, 'num_samples': 100, 'Model': 'RandomForest'}

Evaluating robustness for SVM

HopSkipJump: 100%|██████████| 100/100 [00:06<00:00, 16.48it/s]

{'clean_acc': 0.91, 'adv_acc': 0.12, 'acc_drop': 0.79, 'num_samples': 100, 'Model': 'SVM'}
Skipping XGBoost (XGBoost) for HSJ robustness evaluation.

   clean_acc  adv_acc  acc_drop  num_samples               Model
0       0.93     0.69      0.24          100  LogisticRegression
1       0.96     0.71      0.25          100           NeuralNet
2       0.96     0.20      0.76          100        RandomForest
3       0.91     0.12      0.79          100                 SVM