# Standardized Robustness Pipeline: Poisoning + Evasion (Label Flip, HSJ, Boundary, ZOO)

This notebook runs a standardized robustness pipeline across several models.

## Pipeline steps

1. **Load dataset**
   - Read the CSV, separate features and labels, drop non-feature columns.

2. **Create one canonical split**
   - Make a single train/test split once.
   - The test split is never used for training.

3. **Baseline training + evaluation**
   - Train each model on the clean train set.
   - Evaluate clean accuracy on the held-out test set.

4. **Poisoning (train only)**
   - Apply label-flip poisoning to **training labels only** for multiple flip rates.
   - Train poisoned models and evaluate on the same fixed test set.

5. **ART detectors** (Currently not Included)
   - Wrap models/data for ART.
   - Run `art.defences.detector.poison` and `art.defences.detector.evasion` detectors where enabled.
   - Use detector outputs to filter/flag suspicious samples, then retrain and re-evaluate.

6. **Adversarial training (rounds)**
   - For each round:
     1. Train on the current train set.
     2. Generate adversarial examples from **train only** using ART against the current model.
     3. Append adversarial rows (with correct labels) to the train set.
     4. Retrain and re-evaluate.
   - Adversarial examples are regenerated each round.

7. **Robustness evaluation under attack**
   - Generate adversarial examples on a subset of the test set using ART attacks (e.g., HSJ, ZOO; Boundary skipped for NN).
   - Record clean accuracy, adversarial accuracy, and accuracy drop.

8. **Results table**
   - All metrics are collected into one dataframe (`results_df`) with columns for model, phase, round, attack, and accuracies.

In [50]:
# ===== Imports =====
import os
import json
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Your model runners (expected to exist in your project)
# NOTE: If running this notebook outside your project root, set PYTHONPATH accordingly.
from MachineLearning.LogReg.LogisticRegression_ML import run_best_model as run_logreg
from MachineLearning.NeuralNetworks.NeuralNet_ML import run_best_model as run_neuralnet
from MachineLearning.RandomForest.RandomForest_ML import run_best_model as run_randomforest
from MachineLearning.SVM.SVM_ML import run_best_model as run_svm
from MachineLearning.XGBoost.XGBoost_ML import run_best_model as run_xgboost

# ART: import SklearnClassifier in a way that avoids importing KerasClassifier
# (some ART installs break if keras-related utils are missing).
try:
    from art.estimators.classification.scikitlearn import SklearnClassifier
except Exception:
    from art.estimators.classification import SklearnClassifier

from art.attacks.evasion import HopSkipJump, BoundaryAttack, ZooAttack

RNG = np.random.default_rng(42)

import warnings
warnings.filterwarnings(
    "ignore",
    message="X does not have valid feature names",
    category=UserWarning,
)

In [ ]:
# ===== Configuration =====
DATASET_PATH = "CSVs\\dataset.csv"  # change if needed
LABEL_COL = "anomaly"

# Columns often present in your project; will be dropped from features if they exist
DROP_COLS = {"anomaly", "timestamp", "channel", "label", "segment", "train"}

# Train/test split (canonical, used for ALL models & attacks)
TEST_SIZE = 0.2
SPLIT_RANDOM_STATE = 42

# Attack budget knobs (keep realistic)
EVAL_ATTACK_SAMPLES = 200      # number of test points to attack per model/attack
TRAIN_ADV_SAMPLES = 500        # number of train points to adversarially augment per round
ROUNDS = 2                     # adversarial training rounds (Option B)

# Label flip poisoning knobs
LABEL_FLIP_RATES = [0.05, 0.10, 0.20]

# Attack configs
HSJ_KWARGS = dict(
    max_iter=15,      # 15
    max_eval=1500,    # down from 5000
    init_eval=25,     # down from 50
    init_size=200,    # down from 1000
    targeted=False,
    norm=2
)

HSJ_TRAIN_KWARGS = dict(
    max_iter=8,       # 10 -> 8
    max_eval=300,     # keep
    init_eval=25,     # keep
    init_size=200,    # 1000 -> 200
    targeted=False,
    norm=2
)

BOUNDARY_KWARGS = dict(
    targeted=False,
    max_iter=200,     # 1000 -> 200
    init_size=10
)
ZOO_KWARGS = dict(
    max_iter=5, 
    binary_search_steps=1, 
    nb_parallel=1, 
    batch_size=1
)


# ===== Detection + Retraining (Poison Robustness) =====
# DETECTORS: pick one or more. "LOSS_FILTER" is a built-in fallback that works without ART.
DETECTORS = ["LOSS_FILTER"]  # e.g., ["LOSS_FILTER", "ART_SPECTRAL"] if available in your ART install

# How aggressively to filter suspected poison points (LOSS_FILTER):
LOSS_FILTER_REMOVE_FRAC = 0.10  # remove top 10% highest-loss points from the poisoned training set

# Retraining rounds after filtering (usually 1 is enough for label-flip)
RETRAIN_ROUNDS = 1


# Evasion detectors (run on adversarial examples at test-time)
# Use names like "ART_EVASION::<ClassName>" from art.defences.detector.evasion
EVASION_DETECTORS = []  # e.g., ["ART_EVASION::BinaryInputDetector"]

# Detector kwargs (optional). Keys are class names without prefix.
POISON_DETECTOR_KWARGS = {
    # "ActivationDefence": {...},
}
EVASION_DETECTOR_KWARGS = {
    # "BinaryInputDetector": {...},
}

In [52]:
# ===== Load dataset and create canonical split =====
assert os.path.exists(DATASET_PATH), f"Dataset not found at: {DATASET_PATH}"

df = pd.read_csv(DATASET_PATH)

# Build feature columns (keep only non-label columns; drop known metadata columns if present)
feature_cols = [c for c in df.columns if c not in DROP_COLS and c != LABEL_COL]

# Keep only numeric features for attacks; if you have categorical columns, encode them before this notebook.
X_all = df[feature_cols].to_numpy(dtype=np.float32)
y_all = df[LABEL_COL].to_numpy(dtype=int)

# Ensure labels are 0..K-1
_, y_all = np.unique(y_all, return_inverse=True)

X_train, X_test, y_train, y_test = train_test_split(
    X_all, y_all, test_size=TEST_SIZE, random_state=SPLIT_RANDOM_STATE, stratify=y_all
)

print("Train:", X_train.shape, y_train.shape, "classes:", len(np.unique(y_train)))
print("Test :", X_test.shape, y_test.shape)

Train: (1698, 19) (1698,) classes: 2
Test : (425, 19) (425,)

In [53]:
# ===== Helpers: build train-only CSVs for your existing model runners =====
# Your run_best_model functions read from CSV and do their own internal split.
# To enforce "never train on test", we give them TRAIN-ONLY CSVs.
# We then evaluate the returned trained pipeline on our held-out X_test/y_test.

WORK_DIR = "StandardizedRuns"
os.makedirs(WORK_DIR, exist_ok=True)

def make_train_df_from_arrays(X_tr: np.ndarray, y_tr: np.ndarray) -> pd.DataFrame:
    out = pd.DataFrame(X_tr, columns=feature_cols)
    out[LABEL_COL] = y_tr
    return out

def save_train_csv(df_train: pd.DataFrame, name: str) -> str:
    path = os.path.join(WORK_DIR, name)
    df_train.to_csv(path, index=False)
    return path

def fit_model_with_runner(model_name: str, runner_fn, train_csv_path: str):
    # Use a more reasonable internal split than some module defaults.
    # Many of your modules default to test_size=0.80 (very large). Override to 0.2.
    pipe, _internal_X_test, _internal_y_test = runner_fn(
        path=train_csv_path,
        test_size=0.2,
        random_state=SPLIT_RANDOM_STATE
    )
    return pipe

def eval_clean(pipe, X: np.ndarray, y: np.ndarray) -> float:
    y_pred = pipe.predict(X)
    return float(accuracy_score(y, y_pred))

In [54]:
# ===== ART helpers (no detectors) =====




def wrap_art(pipe, X_ref: np.ndarray) -> SklearnClassifier:
    # clip_values: pragmatic min/max bound from training data
    clip_values = (float(np.min(X_ref)), float(np.max(X_ref)))
    return SklearnClassifier(model=pipe, clip_values=clip_values)

def predict_labels_art(art_clf: SklearnClassifier, X: np.ndarray) -> np.ndarray:
    preds = np.asarray(art_clf.predict(X))
    if preds.ndim == 1:
        return preds.astype(int)
    return np.argmax(preds, axis=1)

def sample_subset(X: np.ndarray, y: np.ndarray, n: int, rng=RNG):
    if n >= len(X):
        return X, y
    idx = rng.choice(len(X), size=n, replace=False)
    return X[idx], y[idx]

def attack_success_rate(y_true: np.ndarray, y_pred_clean: np.ndarray, y_pred_adv: np.ndarray) -> float:
    mask = (y_pred_clean == y_true)
    if mask.sum() == 0:
        return float('nan')
    return float((y_pred_adv[mask] != y_true[mask]).mean())

def eval_under_attack(attack_name: str, art_clf: SklearnClassifier, X_eval: np.ndarray, y_eval: np.ndarray):
    # Generate adversarial examples for evaluation subset and compute metrics.
    if attack_name == "HSJ":
        atk = HopSkipJump(classifier=art_clf, **HSJ_KWARGS)
        X_adv = atk.generate(x=X_eval, y=y_eval)
    elif attack_name == "Boundary":
        # Skip Boundary for NN (sklearn MLP) because BoundaryAttack can produce NaNs
        try:
            m = getattr(art_clf, "model", None)

            # unwrap common wrapper
            if hasattr(m, "base_model"):
                m = m.base_model

            # unwrap sklearn Pipeline -> final estimator
            if hasattr(m, "steps") and len(m.steps) > 0:
                m = m.steps[-1][1]

            if m is not None and m.__class__.__name__ == "MLPClassifier":
                return np.nan, np.nan, np.nan, np.nan, {}
        except Exception:
            pass

        atk = BoundaryAttack(estimator=art_clf, **BOUNDARY_KWARGS)
        X_adv = atk.generate(x=X_eval, y=y_eval)

    elif attack_name == "ZOO":
        atk = ZooAttack(classifier=art_clf, **ZOO_KWARGS)
        # ZOO often expects one-hot labels in some setups, but can work with integers depending on estimator.
        # We'll try integer labels first; if it errors, we fall back to simple one-hot.
        try:
            X_adv = atk.generate(x=X_eval, y=y_eval)
        except Exception:
            k = int(len(np.unique(y_train)))
            y_oh = np.zeros((len(y_eval), k), dtype=np.float32)
            y_oh[np.arange(len(y_eval)), y_eval.astype(int)] = 1.0
            X_adv = atk.generate(x=X_eval, y=y_oh)
    else:
        raise ValueError(f"Unknown attack: {attack_name}")

    X_adv = np.asarray(X_adv, dtype=np.float32)

    y_pred_clean = predict_labels_art(art_clf, X_eval)
    y_pred_adv = predict_labels_art(art_clf, X_adv)


    ev_det_metrics = run_evasion_detectors_on_adv(X_adv, y_pred_adv)
    clean_acc = float(accuracy_score(y_eval, y_pred_clean))
    adv_acc = float(accuracy_score(y_eval, y_pred_adv))
    drop = clean_acc - adv_acc
    asr = attack_success_rate(y_eval, y_pred_clean, y_pred_adv)
    return clean_acc, adv_acc, drop, asr, ev_det_metrics


def _try_import_art_detectors():
    """Best-effort import for ART detector modules. Returns (poison_mod, evasion_mod) or (None, None)."""
    try:
        import art  # noqa: F401
        from art.defences.detector import poison as poison_mod
        from art.defences.detector import evasion as evasion_mod
        return poison_mod, evasion_mod
    except Exception:
        return None, None

def list_art_detector_classes():
    """List available class names in art.defences.detector.poison and .evasion (if installed)."""
    poison_mod, evasion_mod = _try_import_art_detectors()
    out = {"poison": [], "evasion": []}
    import inspect
    if poison_mod is not None:
        for name, obj in vars(poison_mod).items():
            if inspect.isclass(obj) and obj.__module__.startswith("art."):
                out["poison"].append(name)
    if evasion_mod is not None:
        for name, obj in vars(evasion_mod).items():
            if inspect.isclass(obj) and obj.__module__.startswith("art."):
                out["evasion"].append(name)
    out["poison"].sort()
    out["evasion"].sort()
    return out

def _instantiate_art_class(mod, class_name: str, kwargs: dict, *args):
    """Instantiate class from an ART module, filtering kwargs to match the constructor signature."""
    import inspect
    cls = getattr(mod, class_name, None)
    if cls is None:
        raise ImportError(f"ART class not found: {class_name}")
    sig = None
    try:
        sig = inspect.signature(cls.__init__)
    except Exception:
        sig = None
    if sig is not None:
        valid = {k: v for k, v in (kwargs or {}).items() if k in sig.parameters}
    else:
        valid = kwargs or {}
    return cls(*args, **valid)

def run_evasion_detectors_on_adv(X_adv: np.ndarray, y_pred_adv: np.ndarray):
    """Run configured EVASION_DETECTORS and return dict of metrics."""
    metrics = {}
    if not EVASION_DETECTORS:
        return metrics

    _, evasion_mod = _try_import_art_detectors()
    if evasion_mod is None:
        for det in EVASION_DETECTORS:
            metrics[f"evasion_det::{det}"] = np.nan
        return metrics

    import numpy as np
    for det_name in EVASION_DETECTORS:
        if not det_name.startswith("ART_EVASION::"):
            continue
        class_name = det_name.split("::", 1)[1]
        kwargs = EVASION_DETECTOR_KWARGS.get(class_name, {}) if "EVASION_DETECTOR_KWARGS" in globals() else {}
        try:
            det = _instantiate_art_class(evasion_mod, class_name, kwargs)
            # Try common APIs
            if hasattr(det, "detect"):
                out = det.detect(X_adv)  # some detectors take only x
            elif hasattr(det, "predict"):
                out = det.predict(X_adv)
            else:
                raise AttributeError("Detector has no detect/predict method")
            out = np.asarray(out).ravel()
            # Interpret: if boolean -> True means detected; if scores -> threshold at 0.5 (best-effort)
            if out.dtype == bool:
                detected = out
            else:
                detected = out > 0.5
            metrics[f"evasion_det::{class_name}::detected_rate"] = float(np.mean(detected))
        except Exception:
            metrics[f"evasion_det::{class_name}::detected_rate"] = np.nan
    return metrics

In [55]:
# ===== Poison detection + retraining helpers =====
# Supports built-in LOSS_FILTER and best-effort ART poison detectors from art.defences.detector.poison
# Goal: Train -> Poison -> Detect (on poisoned train) -> Retrain -> Test

def per_sample_log_loss_from_proba(y_true: np.ndarray, proba: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """Cross-entropy / log-loss per sample given predicted probabilities."""
    y_true = np.asarray(y_true, dtype=int)
    proba = np.asarray(proba, dtype=np.float64)
    proba = np.clip(proba, eps, 1.0 - eps)
    if proba.ndim == 1:
        # binary edge case: proba = P(class=1)
        proba = np.stack([1.0 - proba, proba], axis=1)
    return -np.log(proba[np.arange(len(y_true)), y_true])

def loss_filter_detector(pipe, X_train: np.ndarray, y_train: np.ndarray, remove_frac: float) -> np.ndarray:
    """Return a boolean mask of points to KEEP (True = keep)."""
    # works for sklearn-like pipelines with predict_proba
    if not hasattr(pipe, "predict_proba"):
        # fallback: use ART prediction (already handles logits/onehot)
        proba = pipe.predict(X_train)
    else:
        proba = pipe.predict_proba(X_train)

    losses = per_sample_log_loss_from_proba(y_train, proba)
    n = len(losses)
    k = int(max(1, round(remove_frac * n)))
    worst_idx = np.argsort(losses)[-k:]  # highest loss = most suspicious for label-noise/flip
    keep = np.ones(n, dtype=bool)
    keep[worst_idx] = False
    return keep

def try_art_poison_detector(detector_name: str, art_clf, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
    """Optional: use ART's poisoning detectors if available.
    Returns keep-mask (True = keep). If detector isn't available, raises ImportError/AttributeError.
    """
    name = detector_name.upper()

    # NOTE: ART detector class names vary by version; these imports are best-effort.
    # If your version differs, search your ART docs for 'poison' defenses and adapt here.
    if name in ["ART_SPECTRAL", "SPECTRAL", "SPECTRAL_SIGNATURE"]:
        try:
            from art.defences.detector.poison import SpectralSignatureDefense
        except Exception as e:
            raise ImportError("SpectralSignatureDefense import failed. Check your ART version.") from e

        # SpectralSignatureDefense API differs across versions. This is a common pattern:
        defence = SpectralSignatureDefense(classifier=art_clf, x_train=X_train, y_train=y_train)
        report = defence.detect_poison()
        # Common conventions: report might include 'is_clean' or 'poisonous_indices'
        if isinstance(report, dict) and "is_clean" in report:
            return np.asarray(report["is_clean"], dtype=bool)
        if isinstance(report, dict) and "poisonous_indices" in report:
            keep = np.ones(len(X_train), dtype=bool)
            keep[np.asarray(report["poisonous_indices"], dtype=int)] = False
            return keep
        raise RuntimeError("Unexpected SpectralSignatureDefense output; inspect `report` and adapt.")

    elif name in ["ART_ACTIVATION", "ACTIVATION_DEFENCE", "ACTIVATION"]:
        try:
            from art.defences.detector.poison import ActivationDefence
        except Exception as e:
            raise ImportError("ActivationDefence import failed. Check your ART version.") from e

        defence = ActivationDefence(classifier=art_clf, x_train=X_train, y_train=y_train)
        report = defence.detect_poison()
        if isinstance(report, dict) and "is_clean" in report:
            return np.asarray(report["is_clean"], dtype=bool)
        if isinstance(report, dict) and "poisonous_indices" in report:
            keep = np.ones(len(X_train), dtype=bool)
            keep[np.asarray(report["poisonous_indices"], dtype=int)] = False
            return keep
        raise RuntimeError("Unexpected ActivationDefence output; inspect `report` and adapt.")
    else:
        raise ValueError(f"Unknown detector_name: {detector_name}")

def detect_poison(detector_name: str, pipe, art_clf, X_train: np.ndarray, y_train: np.ndarray, remove_frac: float) -> np.ndarray:
    """Unified detection interface returning keep-mask."""
    if detector_name.upper() == "LOSS_FILTER":
        return loss_filter_detector(pipe, X_train, y_train, remove_frac)
    else:
        return try_art_poison_detector(detector_name, art_clf, X_train, y_train)

def score_detection(keep_mask: np.ndarray, poison_indices: list[int]) -> dict:
    """Compute simple detection metrics if we know the poison indices."""
    n = len(keep_mask)
    poison = np.zeros(n, dtype=bool)
    poison[np.asarray(poison_indices, dtype=int)] = True

    predicted_poison = ~keep_mask

    tp = int(np.sum(predicted_poison & poison))
    fp = int(np.sum(predicted_poison & ~poison))
    fn = int(np.sum((~predicted_poison) & poison))
    tn = int(np.sum((~predicted_poison) & (~poison)))

    precision = tp / (tp + fp) if (tp + fp) else np.nan
    recall = tp / (tp + fn) if (tp + fn) else np.nan
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else np.nan

    return {
        "det_tp": tp, "det_fp": fp, "det_fn": fn, "det_tn": tn,
        "det_precision": float(precision) if precision==precision else np.nan,
        "det_recall": float(recall) if recall==recall else np.nan,
        "det_f1": float(f1) if f1==f1 else np.nan,
        "det_flagged_frac": float(np.mean(predicted_poison)),
    }


def run_art_poison_detector(detector_name: str, art_clf: SklearnClassifier, X_train: np.ndarray, y_train: np.ndarray) -> np.ndarray:
    """Return a boolean keep mask using an ART poison detector (best-effort, API varies by ART version)."""
    import numpy as np

    poison_mod, _ = _try_import_art_detectors()
    if poison_mod is None:
        raise ImportError("ART is not installed or art.defences.detector.poison is unavailable in this environment.")

    class_name = detector_name.split("::", 1)[1]
    kwargs = POISON_DETECTOR_KWARGS.get(class_name, {}) if "POISON_DETECTOR_KWARGS" in globals() else {}

    det = _instantiate_art_class(poison_mod, class_name, kwargs, art_clf)

    # Try common methods / return patterns
    suspected = None

    # 1) detect_poison(x, y) -> indices / mask / dict
    if hasattr(det, "detect_poison"):
        out = det.detect_poison(X_train, y_train)
        suspected = out

    # 2) detect(x, y) -> indices / mask / scores
    elif hasattr(det, "detect"):
        try:
            suspected = det.detect(X_train, y_train)
        except TypeError:
            suspected = det.detect(X_train)

    # 3) mitigate(x, y) -> cleaned_x, cleaned_y, report
    elif hasattr(det, "mitigate"):
        out = det.mitigate(X_train, y_train)
        suspected = out

    # Normalize output into keep_mask
    n = len(X_train)
    keep_mask = np.ones(n, dtype=bool)

    def _mask_from_indices(idxs):
        m = np.ones(n, dtype=bool)
        m[np.asarray(idxs, dtype=int)] = False
        return m

    if suspected is None:
        raise RuntimeError(f"{class_name}: could not run detector (no supported method found).")

    # If output is tuple, try to find indices-like thing
    if isinstance(suspected, tuple) or isinstance(suspected, list):
        # Find any 1D int-like array
        for item in suspected:
            arr = np.asarray(item)
            if arr.ndim == 1 and arr.size <= n:
                # could be indices or boolean mask
                if arr.dtype == bool and arr.size == n:
                    keep_mask = arr
                    return keep_mask
                # indices heuristic: integer + within range
                if np.issubdtype(arr.dtype, np.integer):
                    keep_mask = _mask_from_indices(arr)
                    return keep_mask
        # If we got cleaned arrays, infer kept indices by matching (fallback: keep all)
        return keep_mask

    # If dict-like
    if isinstance(suspected, dict):
        # common keys
        for k in ["suspected_poison", "poison_indices", "indices", "detected_poison"]:
            if k in suspected:
                arr = np.asarray(suspected[k])
                if arr.dtype == bool and arr.size == n:
                    return arr
                if np.issubdtype(arr.dtype, np.integer):
                    return _mask_from_indices(arr)
        # scores key
        for k in ["scores", "score", "anomaly_score"]:
            if k in suspected:
                scores = np.asarray(suspected[k]).ravel()
                if scores.size == n:
                    # remove top fraction if user provided remove_frac, else 10%
                    frac = float(kwargs.get("remove_frac", LOSS_FILTER_REMOVE_FRAC if "LOSS_FILTER_REMOVE_FRAC" in globals() else 0.10))
                    k_remove = int(np.ceil(frac * n))
                    bad = np.argsort(scores)[-k_remove:]
                    return _mask_from_indices(bad)
        return keep_mask

    # ndarray
    arr = np.asarray(suspected)
    if arr.dtype == bool and arr.size == n:
        return arr
    if np.issubdtype(arr.dtype, np.integer):
        return _mask_from_indices(arr)
    if arr.size == n:
        # treat as scores
        frac = float(kwargs.get("remove_frac", LOSS_FILTER_REMOVE_FRAC if "LOSS_FILTER_REMOVE_FRAC" in globals() else 0.10))
        k_remove = int(np.ceil(frac * n))
        bad = np.argsort(arr.ravel())[-k_remove:]
        return _mask_from_indices(bad)

    return keep_mask

def detect_poison(detector_name: str, pipe, art_clf: SklearnClassifier, X_train: np.ndarray, y_train: np.ndarray, poison_indices=None) -> dict:
    """Run poison detector and return dict with keep_mask + detection metrics."""
    import numpy as np

    if detector_name == "LOSS_FILTER":
        keep_mask = loss_filter_detector(pipe, X_train, y_train, remove_frac=LOSS_FILTER_REMOVE_FRAC)
    elif detector_name.startswith("ART_POISON::"):
        keep_mask = run_art_poison_detector(detector_name, art_clf, X_train, y_train)
    else:
        raise ValueError(f"Unknown detector: {detector_name}")

    out = {"keep_mask": keep_mask}
    if poison_indices is not None and len(poison_indices) > 0:
        out.update(score_detection(keep_mask, poison_indices))
    return out

In [56]:
# ===== Poisoning: Label Flip (train-only) =====

def label_flip(y: np.ndarray, flip_rate: float, num_classes: int, rng=RNG) -> tuple[np.ndarray, dict]:
    """Flip labels for a subset of training points. Returns (y_poisoned, meta).

    meta["indices"] are the positions in y that were flipped.
    """
    y = np.asarray(y, dtype=int).copy()
    n = len(y)
    k = int(num_classes)
    m = int(round(flip_rate * n))
    idx = rng.choice(n, size=m, replace=False)

    if k == 2:
        y[idx] = 1 - y[idx]
    else:
        for i in idx:
            choices = [c for c in range(k) if c != y[i]]
            y[i] = rng.choice(choices)

    meta = {"flip_rate": float(flip_rate), "num_flipped": int(m), "indices": idx.tolist()}
    return y, meta

In [57]:
# ===== Standardized experiment runners =====

MODEL_RUNNERS = {
    "LogReg": run_logreg,
    "NeuralNet": run_neuralnet,
    "RandomForest": run_randomforest,
    "SVM": run_svm,
    # "XGBoost": run_xgboost,
}

EVASION_ATTACKS = ["HSJ", "Boundary", "ZOO"]

def _flatten_metrics(d: dict, prefix: str = ""):
    if not d:
        return {}
    return {f"{prefix}{k}": v for k, v in d.items()}


def run_baseline_and_evasion(model_name: str, runner_fn):
    rows = []

    # Train on clean TRAIN ONLY
    train_df = make_train_df_from_arrays(X_train, y_train)
    clean_train_path = save_train_csv(train_df, f"{model_name}_train_clean.csv")
    pipe = fit_model_with_runner(model_name, runner_fn, clean_train_path)

    # Clean eval (full held-out test)
    clean_test_acc = eval_clean(pipe, X_test, y_test)

    # Evasion eval on subset
    art_clf = wrap_art(pipe, X_train)
    X_eval, y_eval = sample_subset(X_test, y_test, EVAL_ATTACK_SAMPLES)

    for atk in EVASION_ATTACKS:
        cacc, aacc, drop, asr, evm = eval_under_attack(atk, art_clf, X_eval, y_eval)
        rows.append({
            "model": model_name,
            "phase": "baseline",
            "attack_type": "evasion",
            "attack": atk,
            "round": 0,
            "clean_test_acc": clean_test_acc,
            "clean_acc_evalsubset": cacc,
            "adv_acc_evalsubset": aacc,
            "acc_drop_evalsubset": drop,
            "attack_success_rate": asr,
            "train_poison_rate": 0.0,
            "train_adv_augmented": 0,
            "eval_attack_samples": len(X_eval),
        })

    return pipe, pd.DataFrame(rows)

def run_label_flip_poisoning(model_name: str, runner_fn, flip_rate: float):
    rows = []

    num_classes = int(np.unique(y_train).size)
    y_poison, meta = label_flip(y_train, flip_rate, num_classes=num_classes)

    train_df_poison = make_train_df_from_arrays(X_train, y_poison)
    poison_path = save_train_csv(train_df_poison, f"{model_name}_train_labelflip_{int(flip_rate*100)}.csv")

    pipe = fit_model_with_runner(model_name, runner_fn, poison_path)

    clean_test_acc = eval_clean(pipe, X_test, y_test)

    # Optional: evaluate evasion robustness after poisoning (often interesting)
    art_clf = wrap_art(pipe, X_train)
    X_eval, y_eval = sample_subset(X_test, y_test, EVAL_ATTACK_SAMPLES)

    for atk in EVASION_ATTACKS:
        cacc, aacc, drop, asr, evm = eval_under_attack(atk, art_clf, X_eval, y_eval)
        rows.append({
            "model": model_name,
            "phase": "poisoned",
            "attack_type": "poison+evasion",
            "attack": f"LabelFlip({flip_rate}) + {atk}",
            "round": 0,
            "clean_test_acc": clean_test_acc,
            "clean_acc_evalsubset": cacc,
            "adv_acc_evalsubset": aacc,
            "acc_drop_evalsubset": drop,
            "attack_success_rate": asr,
            "train_poison_rate": float(flip_rate),
            "train_adv_augmented": 0,
            "eval_attack_samples": len(X_eval),
            "poison_meta": json.dumps({k: v for k, v in meta.items() if k != "indices"}),
        })

    return pd.DataFrame(rows)

def run_adversarial_training(model_name: str, runner_fn, train_attack: str = "HSJ"):
    rows = []

    # Start with clean train
    X_tr = X_train.copy()
    y_tr = y_train.copy()
    augmented = 0

    for r in range(ROUNDS + 1):
        # Train current model on current train set (clean + accumulated adv)
        train_df = make_train_df_from_arrays(X_tr, y_tr)
        train_path = save_train_csv(train_df, f"{model_name}_train_advtrain_round{r}.csv")
        pipe = fit_model_with_runner(model_name, runner_fn, train_path)

        # Evaluate on full clean test
        clean_test_acc = eval_clean(pipe, X_test, y_test)

        # Evaluate evasion robustness on subset (HSJ/Boundary/ZOO)
        art_clf = wrap_art(pipe, X_tr)
        X_eval, y_eval = sample_subset(X_test, y_test, EVAL_ATTACK_SAMPLES)

        for atk in EVASION_ATTACKS:
            cacc, aacc, drop, asr, evm = eval_under_attack(atk, art_clf, X_eval, y_eval)
            rows.append({
                "model": model_name,
                "phase": "advtrain",
                "attack_type": "evasion",
                "attack": atk,
                "round": r,
                "clean_test_acc": clean_test_acc,
                "clean_acc_evalsubset": cacc,
                "adv_acc_evalsubset": aacc,
                "acc_drop_evalsubset": drop,
                "attack_success_rate": asr,
                "train_poison_rate": 0.0,
                "train_adv_augmented": augmented,
                "eval_attack_samples": len(X_eval),
            })

        if r == ROUNDS:
            break

        # Generate fresh adversarials from TRAIN subset only
        X_sub, y_sub = sample_subset(X_tr, y_tr, TRAIN_ADV_SAMPLES)

        if train_attack == "HSJ":
            atk_train = HopSkipJump(classifier=art_clf, **HSJ_TRAIN_KWARGS)
            X_adv = atk_train.generate(x=X_sub, y=y_sub)
        elif train_attack == "Boundary":
            atk_train = BoundaryAttack(estimator=art_clf, **BOUNDARY_KWARGS)
            X_adv = atk_train.generate(x=X_sub, y=y_sub)
        elif train_attack == "ZOO":
            atk_train = ZooAttack(classifier=art_clf, **ZOO_KWARGS)
            try:
                X_adv = atk_train.generate(x=X_sub, y=y_sub)
            except Exception:
                k = int(len(np.unique(y_train)))
                y_oh = np.zeros((len(y_sub), k), dtype=np.float32)
                y_oh[np.arange(len(y_sub)), y_sub.astype(int)] = 1.0
                X_adv = atk_train.generate(x=X_sub, y=y_oh)
        else:
            raise ValueError(train_attack)

        X_adv = np.asarray(X_adv, dtype=np.float32)

        # Append with correct labels
        X_tr = np.vstack([X_tr, X_adv]).astype(np.float32)
        y_tr = np.concatenate([y_tr, y_sub]).astype(int)
        augmented += len(X_adv)

        print(f"[{model_name}] adv-train round {r} -> {r+1}: +{len(X_adv)} using {train_attack}, train size={len(X_tr)}")

    return pd.DataFrame(rows)

def run_poison_detect_retrain(model_name: str, runner_fn, flip_rate: float, detector_name: str):
    """Train clean -> poison labels -> train poisoned -> detect -> retrain on filtered -> test (+ optional evasion eval)."""
    rows = []

    num_classes = int(len(np.unique(y_train)))

    # 1) Clean training (train-only CSV)
    train_df = make_train_df_from_arrays(X_train, y_train)
    clean_train_path = save_train_csv(train_df, f"{model_name}_train_clean_for_detect.csv")
    pipe_clean = fit_model_with_runner(model_name, runner_fn, clean_train_path)
    clean_test_acc = eval_clean(pipe_clean, X_test, y_test)

    # 2) Poison labels and train poisoned model
    y_poison, meta = label_flip(y_train, flip_rate=flip_rate, num_classes=num_classes)
    poison_df = make_train_df_from_arrays(X_train, y_poison)
    poison_train_path = save_train_csv(poison_df, f"{model_name}_train_poison_flip{flip_rate:.3f}.csv")
    pipe_poison = fit_model_with_runner(model_name, runner_fn, poison_train_path)
    poisoned_test_acc = eval_clean(pipe_poison, X_test, y_test)

    # 3) Detect poison points (on poisoned training set)
    art_poison = wrap_art(pipe_poison, X_train)
    keep_mask = detect_poison(detector_name, pipe_poison, art_poison, X_train, y_poison, LOSS_FILTER_REMOVE_FRAC)
    det_metrics = score_detection(keep_mask, meta["indices"])

    # 4) Retrain on filtered dataset (optionally multiple rounds)
    X_filt = X_train[keep_mask]
    y_filt = y_poison[keep_mask]

    pipe_rt = pipe_poison
    rt_test_acc = poisoned_test_acc
    for rr in range(RETRAIN_ROUNDS):
        filt_df = make_train_df_from_arrays(X_filt, y_filt)
        filt_train_path = save_train_csv(
            filt_df,
            f"{model_name}_train_filtered_{detector_name}_r{rr+1}_flip{flip_rate:.3f}.csv"
        )
        pipe_rt = fit_model_with_runner(model_name, runner_fn, filt_train_path)
        rt_test_acc = eval_clean(pipe_rt, X_test, y_test)

    # 5) Optional: evasion evaluation after retraining
    art_rt = wrap_art(pipe_rt, X_filt)
    X_eval, y_eval = sample_subset(X_test, y_test, EVAL_ATTACK_SAMPLES)

    # Summary rows (clean, poisoned, retrained)
    base_common = {k: det_metrics.get(k, np.nan) for k in det_metrics}
    rows.append({
        "model": model_name,
        "phase": "clean",
        "attack_type": "none",
        "attack": "none",
        "round": 0,
        "clean_test_acc": float(clean_test_acc),
        "clean_acc_evalsubset": np.nan,
        "adv_acc_evalsubset": np.nan,
        "acc_drop_evalsubset": np.nan,
        "attack_success_rate": np.nan,
        "train_poison_rate": 0.0,
        "detector": None,
        "train_adv_augmented": 0,
        "eval_attack_samples": len(X_eval),
        "poison_meta": None,
        **base_common,
    })
    rows.append({
        "model": model_name,
        "phase": "poisoned",
        "attack_type": "poison",
        "attack": f"LabelFlip({flip_rate})",
        "round": 0,
        "clean_test_acc": float(poisoned_test_acc),
        "clean_acc_evalsubset": np.nan,
        "adv_acc_evalsubset": np.nan,
        "acc_drop_evalsubset": np.nan,
        "attack_success_rate": np.nan,
        "train_poison_rate": float(flip_rate),
        "detector": None,
        "train_adv_augmented": 0,
        "eval_attack_samples": len(X_eval),
        "poison_meta": json.dumps({k: v for k, v in meta.items() if k != "indices"}),
        **base_common,
    })
    rows.append({
        "model": model_name,
        "phase": "detected_retrained",
        "attack_type": "poison",
        "attack": f"LabelFlip({flip_rate}) + Detect({detector_name}) + Retrain({RETRAIN_ROUNDS})",
        "round": 0,
        "clean_test_acc": float(rt_test_acc),
        "clean_acc_evalsubset": np.nan,
        "adv_acc_evalsubset": np.nan,
        "acc_drop_evalsubset": np.nan,
        "attack_success_rate": np.nan,
        "train_poison_rate": float(flip_rate),
        "detector": detector_name,
        "train_adv_augmented": 0,
        "eval_attack_samples": len(X_eval),
        "poison_meta": json.dumps({k: v for k, v in meta.items() if k != "indices"}),
        **base_common,
    })

    for atk in EVASION_ATTACKS:
        cacc, aacc, drop, asr, evm = eval_under_attack(atk, art_rt, X_eval, y_eval)
        rows.append({
            "model": model_name,
            "phase": "detected_retrained",
            "attack_type": "poison+evasion",
            "attack": f"LabelFlip({flip_rate}) + Detect({detector_name}) + Retrain({RETRAIN_ROUNDS}) + {atk}",
            "round": 0,
            "clean_test_acc": float(rt_test_acc),
            "clean_acc_evalsubset": cacc,
            "adv_acc_evalsubset": aacc,
            "acc_drop_evalsubset": drop,
            "attack_success_rate": asr,
            "train_poison_rate": float(flip_rate),
            "detector": detector_name,
            "train_adv_augmented": 0,
            "eval_attack_samples": len(X_eval),
            "poison_meta": json.dumps({k: v for k, v in meta.items() if k != "indices"}),
            **base_common,
        })

    return pd.DataFrame(rows)

In [58]:
# ===== Run the full standardized suite =====

all_rows = []

for model_name, runner_fn in MODEL_RUNNERS.items():
    print("\n" + "="*80)
    print("MODEL:", model_name)
    print("="*80)

    # Baseline + evasion attacks (clean training)
    _pipe, df_base = run_baseline_and_evasion(model_name, runner_fn)
    all_rows.append(df_base)

    # Poisoning: label flip rates (train poisoned models + evaluate)
    for rate in LABEL_FLIP_RATES:
        df_poison = run_label_flip_poisoning(model_name, runner_fn, rate)
        all_rows.append(df_poison)

        # Detection -> retrain -> evaluate
        for det in DETECTORS:
            try:
                df_det = run_poison_detect_retrain(model_name, runner_fn, flip_rate=rate, detector_name=det)
                all_rows.append(df_det)
            except Exception as e:
                print(f"[{model_name}] Detect/Retrain skipped for detector={det}, rate={rate}: {type(e).__name__}: {e}")

    # Option B: adversarial training (default HSJ) - comment out if too slow
    df_advtrain = run_adversarial_training(model_name, runner_fn, train_attack="HSJ")
    all_rows.append(df_advtrain)

results_df = pd.concat(all_rows, ignore_index=True)
results_df

================================================================================
MODEL: LogReg
================================================================================
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
New best model found! (F1 0.916 > 0.896)
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.981)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       271
           1       0.88      0.81      0.84        69

    accuracy                           0.94       340
   macro avg       0.91      0.89      0.90       340
weighted avg       0.94      0.94      0.94       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     263       8
True 1      13      56

AUC: 0.981

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 698.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack: 100%|██████████| 200/200 [00:41<00:00,  4.86it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 279.86it/s]

Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.899)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       262
           1       0.77      0.78      0.78        78

    accuracy                           0.90       340
   macro avg       0.85      0.86      0.86       340
weighted avg       0.90      0.90      0.90       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     244      18
True 1      17      61

AUC: 0.899

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack: 100%|██████████| 200/200 [01:02<00:00,  3.21it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 283.43it/s]

Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.981)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       271
           1       0.88      0.81      0.84        69

    accuracy                           0.94       340
   macro avg       0.91      0.89      0.90       340
weighted avg       0.94      0.94      0.94       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     263       8
True 1      13      56

AUC: 0.981

=== All results and summaries saved successfully ===
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.871)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.89      0.94      0.92       260
           1       0.77      0.62      0.69        80

    accuracy                           0.87       340
   macro avg       0.83      0.78      0.80       340
weighted avg       0.86      0.87      0.86       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     245      15
True 1      30      50

AUC: 0.871

=== All results and summaries saved successfully ===
[LogReg] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.05: TypeError: object of type 'float' has no len()
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.811)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       248
           1       0.71      0.58      0.63        92

    accuracy                           0.82       340
   macro avg       0.78      0.74      0.76       340
weighted avg       0.81      0.82      0.81       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     226      22
True 1      39      53

AUC: 0.811

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 682.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations:  58%|█████▊    | 117/200 [00:00<00:00, 631.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 691.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 698.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 691.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack: 100%|██████████| 200/200 [00:47<00:00,  4.25it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 270.39it/s]

Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.981)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       271
           1       0.88      0.81      0.84        69

    accuracy                           0.94       340
   macro avg       0.91      0.89      0.90       340
weighted avg       0.94      0.94      0.94       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     263       8
True 1      13      56

AUC: 0.981

=== All results and summaries saved successfully ===
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.798)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       257
           1       0.62      0.61      0.62        83

    accuracy                           0.81       340
   macro avg       0.75      0.75      0.75       340
weighted avg       0.81      0.81      0.81       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     226      31
True 1      32      51

AUC: 0.798

=== All results and summaries saved successfully ===
[LogReg] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.1: TypeError: object of type 'float' has no len()
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.597)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.77      0.86      0.81       231
           1       0.60      0.45      0.52       109

    accuracy                           0.73       340
   macro avg       0.69      0.66      0.66       340
weighted avg       0.72      0.73      0.72       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     199      32
True 1      60      49

AUC: 0.597

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 601.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 609.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack: 100%|██████████| 200/200 [00:54<00:00,  3.65it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 276.37it/s]

Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.981)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       271
           1       0.88      0.81      0.84        69

    accuracy                           0.94       340
   macro avg       0.91      0.89      0.90       340
weighted avg       0.94      0.94      0.94       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     263       8
True 1      13      56

AUC: 0.981

=== All results and summaries saved successfully ===
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.699)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       231
           1       0.57      0.45      0.50       109

    accuracy                           0.71       340
   macro avg       0.67      0.64      0.65       340
weighted avg       0.70      0.71      0.70       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     194      37
True 1      60      49

AUC: 0.699

=== All results and summaries saved successfully ===
[LogReg] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.2: TypeError: object of type 'float' has no len()
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.981)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       271
           1       0.88      0.81      0.84        69

    accuracy                           0.94       340
   macro avg       0.91      0.89      0.90       340
weighted avg       0.94      0.94      0.94       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     263       8
True 1      13      56

AUC: 0.981

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.38it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 696.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 698.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 691.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack: 100%|██████████| 200/200 [00:41<00:00,  4.86it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 283.83it/s]
HopSkipJump: 100%|██████████| 500/500 [00:12<00:00, 39.90it/s]

[LogReg] adv-train round 0 -> 1: +500 using HSJ, train size=2198
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
New best model found! (F1 0.925 > 0.916)
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.976)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       348
           1       0.88      0.85      0.86        92

    accuracy                           0.94       440
   macro avg       0.92      0.91      0.91       440
weighted avg       0.94      0.94      0.94       440


Confusion Matrix:
         Pred 0  Pred 1
True 0     337      11
True 1      14      78

AUC: 0.976

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 24.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 691.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 701.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 696.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 703.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack: 100%|██████████| 200/200 [01:02<00:00,  3.22it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 285.05it/s]
HopSkipJump: 100%|██████████| 500/500 [00:11<00:00, 42.39it/s]

[LogReg] adv-train round 1 -> 2: +500 using HSJ, train size=2698
Using parameters: {'clf__C': 10, 'clf__class_weight': 'balanced', 'clf__penalty': 'l2', 'clf__solver': 'liblinear'}

Saved last run results to Results/LogRegResults\results_logreg.csv
Saved ROC data to Results/LogRegResults\roc_logreg_clean.csv (AUC = 0.974)
Saved summary (AUC + Confusion Matrix) to Results/LogRegResults\logreg_summary.csv

=== Test Set Classification Report ===
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       427
           1       0.84      0.82      0.83       113

    accuracy                           0.93       540
   macro avg       0.90      0.89      0.89       540
weighted avg       0.93      0.93      0.93       540


Confusion Matrix:
         Pred 0  Pred 1
True 0     409      18
True 1      20      93

AUC: 0.974

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:08<00:00, 23.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 686.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 630.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 650.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 684.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 638.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 624.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 681.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 677.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 648.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 689.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 666.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 672.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 661.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 668.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 679.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 657.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 628.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 675.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 644.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 670.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 659.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 663.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 640.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 636.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 646.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 655.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack: 100%|██████████| 200/200 [00:50<00:00,  3.95it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 270.02it/s]

================================================================================
MODEL: NeuralNet
================================================================================
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
New best model found! (F1 0.947 > 0.923)
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       0.98      0.83      0.90        69

    accuracy                           0.96       340
   macro avg       0.97      0.91      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     270       1
True 1      12      57

AUC: 0.987

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 20.53it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 269.66it/s]

Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.866)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.90      0.98      0.94       260
           1       0.91      0.66      0.77        80

    accuracy                           0.91       340
   macro avg       0.91      0.82      0.85       340
weighted avg       0.91      0.91      0.90       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     255       5
True 1      27      53

AUC: 0.866

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 21.06it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 267.49it/s]

Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       0.98      0.83      0.90        69

    accuracy                           0.96       340
   macro avg       0.97      0.91      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     270       1
True 1      12      57

AUC: 0.987

=== All results and summaries saved successfully ===
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.900)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       262
           1       0.88      0.73      0.80        78

    accuracy                           0.91       340
   macro avg       0.90      0.85      0.87       340
weighted avg       0.91      0.91      0.91       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     254       8
True 1      21      57

AUC: 0.900

=== All results and summaries saved successfully ===
[NeuralNet] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.05: TypeError: object of type 'float' has no len()
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.818)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       252
           1       0.85      0.65      0.74        88

    accuracy                           0.88       340
   macro avg       0.87      0.80      0.83       340
weighted avg       0.88      0.88      0.87       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     242      10
True 1      31      57

AUC: 0.818

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:10<00:00, 18.48it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 272.97it/s]

Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       0.98      0.83      0.90        69

    accuracy                           0.96       340
   macro avg       0.97      0.91      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     270       1
True 1      12      57

AUC: 0.987

=== All results and summaries saved successfully ===
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.785)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.84      0.98      0.90       251
           1       0.89      0.46      0.61        89

    accuracy                           0.84       340
   macro avg       0.86      0.72      0.76       340
weighted avg       0.85      0.84      0.83       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     246       5
True 1      48      41

AUC: 0.785

=== All results and summaries saved successfully ===
[NeuralNet] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.1: TypeError: object of type 'float' has no len()
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.681)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.77      0.94      0.85       229
           1       0.78      0.41      0.54       111

    accuracy                           0.77       340
   macro avg       0.77      0.68      0.69       340
weighted avg       0.77      0.77      0.75       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     216      13
True 1      65      46

AUC: 0.681

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 21.52it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 269.66it/s]

Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       0.98      0.83      0.90        69

    accuracy                           0.96       340
   macro avg       0.97      0.91      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     270       1
True 1      12      57

AUC: 0.987

=== All results and summaries saved successfully ===
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.680)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.75      0.93      0.83       227
           1       0.72      0.38      0.50       113

    accuracy                           0.74       340
   macro avg       0.73      0.65      0.66       340
weighted avg       0.74      0.74      0.72       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     210      17
True 1      70      43

AUC: 0.680

=== All results and summaries saved successfully ===
[NeuralNet] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.2: TypeError: object of type 'float' has no len()
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       271
           1       0.98      0.83      0.90        69

    accuracy                           0.96       340
   macro avg       0.97      0.91      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     270       1
True 1      12      57

AUC: 0.987

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 20.56it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 273.35it/s]
HopSkipJump: 100%|██████████| 500/500 [00:14<00:00, 34.83it/s]

[NeuralNet] adv-train round 0 -> 1: +500 using HSJ, train size=2198
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
New best model found! (F1 0.981 > 0.947)
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.990)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       351
           1       1.00      0.93      0.97        89

    accuracy                           0.99       440
   macro avg       0.99      0.97      0.98       440
weighted avg       0.99      0.99      0.99       440


Confusion Matrix:
         Pred 0  Pred 1
True 0     351       0
True 1       6      83

AUC: 0.990

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 21.70it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 256.51it/s]
HopSkipJump: 100%|██████████| 500/500 [00:12<00:00, 39.38it/s]

[NeuralNet] adv-train round 1 -> 2: +500 using HSJ, train size=2698
Using parameters: {'hidden_layer_sizes': '128,64', 'alpha': 0.0001, 'learning_rate_init': 0.01, 'batch_size': 64, 'activation': 'relu', 'solver': 'adam', 'learning_rate': 'adaptive', 'max_iter': 1000, 'early_stopping': True, 'n_iter_no_change': 20, 'random_state': 100}

Saved last run results to Results/NeuralNetworksResults\results_neuralnet.csv
Saved ROC data to Results/NeuralNetworksResults\roc_neuralnet_clean.csv (AUC = 0.987)
Saved summary (AUC + Confusion Matrix) to Results/NeuralNetworksResults\neuralnet_summary.csv

=== Neural Network Test Set Report ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       430
           1       0.99      0.83      0.90       110

    accuracy                           0.96       540
   macro avg       0.97      0.91      0.94       540
weighted avg       0.96      0.96      0.96       540


Confusion Matrix:
         Pred 0  Pred 1
True 0     429       1
True 1      19      91

AUC: 0.987

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:09<00:00, 21.95it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 267.85it/s]

================================================================================
MODEL: RandomForest
================================================================================

Saved last run results to Results/RandomForestResults\results_randomforest.csv
New best model found! (F1 0.948 > 0.924)
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.988)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.94      0.87      0.90        69

    accuracy                           0.96       340
   macro avg       0.95      0.93      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     267       4
True 1       9      60

AUC: 0.988

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [11:36<00:00,  3.48s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.78it/s]
Boundary attack - iterations:  66%|██████▌   | 131/200 [00:06<00:03, 20.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 18.16it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 18.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.82it/s]
Boundary attack: 100%|██████████| 200/200 [06:14<00:00,  1.87s/it]
ZOO: 100%|██████████| 200/200 [00:35<00:00,  5.67it/s]

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.857)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.90      0.97      0.93       259
           1       0.87      0.67      0.76        81

    accuracy                           0.90       340
   macro avg       0.89      0.82      0.85       340
weighted avg       0.90      0.90      0.89       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     251       8
True 1      27      54

AUC: 0.857

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [13:25<00:00,  4.03s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.16it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.88it/s]
Boundary attack - iterations:  47%|████▋     | 94/200 [00:05<00:05, 18.00it/s]
Boundary attack - iterations:  63%|██████▎   | 126/200 [00:06<00:04, 18.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.25it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.38it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 22.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.85it/s]
Boundary attack: 100%|██████████| 200/200 [09:10<00:00,  2.75s/it]
ZOO: 100%|██████████| 200/200 [00:34<00:00,  5.84it/s]

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.988)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.94      0.87      0.90        69

    accuracy                           0.96       340
   macro avg       0.95      0.93      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     267       4
True 1       9      60

AUC: 0.988

=== All results and summaries saved successfully ===

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.958)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       260
           1       0.93      0.71      0.81        80

    accuracy                           0.92       340
   macro avg       0.93      0.85      0.88       340
weighted avg       0.92      0.92      0.92       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     256       4
True 1      23      57

AUC: 0.958

=== All results and summaries saved successfully ===
[RandomForest] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.05: TypeError: object of type 'float' has no len()

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.847)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.89      0.98      0.93       251
           1       0.92      0.66      0.77        89

    accuracy                           0.90       340
   macro avg       0.91      0.82      0.85       340
weighted avg       0.90      0.90      0.89       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     246       5
True 1      30      59

AUC: 0.847

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [16:38<00:00,  4.99s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.16it/s]
Boundary attack - iterations:  82%|████████▏ | 164/200 [00:12<00:02, 13.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.66it/s]
Boundary attack - iterations:  96%|█████████▋| 193/200 [00:14<00:00, 12.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.25it/s]
Boundary attack - iterations:  94%|█████████▍| 188/200 [00:14<00:00, 13.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.96it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.38it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:17<00:00, 11.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.50it/s]
Boundary attack - iterations:  48%|████▊     | 97/200 [00:07<00:07, 13.04it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.04it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.04it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 14.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.49it/s]
Boundary attack: 100%|██████████| 200/200 [37:59<00:00, 11.40s/it]
ZOO: 100%|██████████| 200/200 [00:50<00:00,  4.00it/s]

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.988)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.94      0.87      0.90        69

    accuracy                           0.96       340
   macro avg       0.95      0.93      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     267       4
True 1       9      60

AUC: 0.988

=== All results and summaries saved successfully ===

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.802)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.88      0.95      0.91       249
           1       0.82      0.64      0.72        91

    accuracy                           0.86       340
   macro avg       0.85      0.79      0.81       340
weighted avg       0.86      0.86      0.86       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     236      13
True 1      33      58

AUC: 0.802

=== All results and summaries saved successfully ===
[RandomForest] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.1: TypeError: object of type 'float' has no len()

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.668)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.77      0.88      0.82       232
           1       0.63      0.45      0.53       108

    accuracy                           0.74       340
   macro avg       0.70      0.66      0.67       340
weighted avg       0.73      0.74      0.73       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     203      29
True 1      59      49

AUC: 0.668

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [18:08<00:00,  5.44s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 22.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.04it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.75it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 16.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 16.85it/s]
Boundary attack: 100%|██████████| 200/200 [09:04<00:00,  2.72s/it]
ZOO: 100%|██████████| 200/200 [00:43<00:00,  4.60it/s]

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.988)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.94      0.87      0.90        69

    accuracy                           0.96       340
   macro avg       0.95      0.93      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     267       4
True 1       9      60

AUC: 0.988

=== All results and summaries saved successfully ===

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.678)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.79      0.90      0.84       234
           1       0.68      0.47      0.56       106

    accuracy                           0.77       340
   macro avg       0.74      0.69      0.70       340
weighted avg       0.76      0.77      0.75       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     211      23
True 1      56      50

AUC: 0.678

=== All results and summaries saved successfully ===
[RandomForest] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.2: TypeError: object of type 'float' has no len()

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.988)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       271
           1       0.94      0.87      0.90        69

    accuracy                           0.96       340
   macro avg       0.95      0.93      0.94       340
weighted avg       0.96      0.96      0.96       340


Confusion Matrix:
         Pred 0  Pred 1
True 0     267       4
True 1       9      60

AUC: 0.988

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [14:03<00:00,  4.22s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 23.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 23.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.25it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.96it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 18.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.48it/s]
Boundary attack - iterations:  48%|████▊     | 96/200 [00:04<00:05, 19.58it/s]
Boundary attack: 100%|██████████| 200/200 [06:55<00:00,  2.08s/it]
ZOO: 100%|██████████| 200/200 [00:36<00:00,  5.46it/s]
HopSkipJump: 100%|██████████| 500/500 [26:11<00:00,  3.14s/it]

[RandomForest] adv-train round 0 -> 1: +500 using HSJ, train size=2198

Saved last run results to Results/RandomForestResults\results_randomforest.csv
New best model found! (F1 0.969 > 0.948)
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.994)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       351
           1       0.96      0.92      0.94        89

    accuracy                           0.98       440
   macro avg       0.97      0.96      0.96       440
weighted avg       0.98      0.98      0.98       440


Confusion Matrix:
         Pred 0  Pred 1
True 0     348       3
True 1       7      82

AUC: 0.994

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [11:11<00:00,  3.36s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 22.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 22.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 22.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:10<00:00, 19.25it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 20.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 22.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:09<00:00, 21.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:08<00:00, 24.95it/s]
Boundary attack: 100%|██████████| 200/200 [05:10<00:00,  1.55s/it]
ZOO: 100%|██████████| 200/200 [00:34<00:00,  5.84it/s]
HopSkipJump: 100%|██████████| 500/500 [27:16<00:00,  3.27s/it]

[RandomForest] adv-train round 1 -> 2: +500 using HSJ, train size=2698

Saved last run results to Results/RandomForestResults\results_randomforest.csv
Saved ROC data to Results/RandomForestResults\roc_randomforest_clean.csv (AUC = 0.991)
Saved summary (AUC + Confusion Matrix) to Results/RandomForestResults\randomforest_summary.csv

=== Random Forest Test Set Report ===
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       429
           1       0.95      0.91      0.93       111

    accuracy                           0.97       540
   macro avg       0.96      0.95      0.96       540
weighted avg       0.97      0.97      0.97       540


Confusion Matrix:
         Pred 0  Pred 1
True 0     424       5
True 1      10     101

AUC: 0.991

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [17:20<00:00,  5.20s/it]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 14.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 17.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:11<00:00, 18.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:13<00:00, 15.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:12<00:00, 15.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.75it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.79it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.16it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:14<00:00, 13.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 13.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 12.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:16<00:00, 11.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:15<00:00, 12.72it/s]
Boundary attack: 100%|██████████| 200/200 [17:05<00:00,  5.13s/it]
ZOO: 100%|██████████| 200/200 [01:03<00:00,  3.17it/s]

================================================================================
MODEL: SVM
================================================================================

Saved last run results to Results/SVMResults\results_svm.csv
New best model found! (F1 0.914 > 0.899)
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.922)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.94      0.99      0.96      1217
           1       0.97      0.73      0.83       312

    accuracy                           0.94      1529
   macro avg       0.95      0.86      0.90      1529
weighted avg       0.94      0.94      0.94      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1209       8
True 1      84     228

AUC: 0.922

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:11<00:00, 17.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 552.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 576.53it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 601.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 620.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.65it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 578.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 560.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack: 100%|██████████| 200/200 [00:34<00:00,  5.72it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 217.13it/s]

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.849)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.87      0.99      0.93      1162
           1       0.95      0.55      0.70       367

    accuracy                           0.88      1529
   macro avg       0.91      0.77      0.81      1529
weighted avg       0.89      0.88      0.87      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1152      10
True 1     166     201

AUC: 0.849

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:11<00:00, 17.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 581.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 519.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.16it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 546.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 533.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 523.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 516.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 525.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.31it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 583.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 583.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 573.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 581.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.24it/s]
Boundary attack: 100%|██████████| 200/200 [01:04<00:00,  3.11it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 229.68it/s]

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.922)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.94      0.99      0.96      1217
           1       0.97      0.73      0.83       312

    accuracy                           0.94      1529
   macro avg       0.95      0.86      0.90      1529
weighted avg       0.94      0.94      0.94      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1209       8
True 1      84     228

AUC: 0.922

=== All results and summaries saved successfully ===

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.838)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.89      0.98      0.93      1167
           1       0.88      0.59      0.71       362

    accuracy                           0.89      1529
   macro avg       0.89      0.78      0.82      1529
weighted avg       0.89      0.89      0.88      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1139      28
True 1     147     215

AUC: 0.838

=== All results and summaries saved successfully ===
[SVM] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.05: TypeError: object of type 'float' has no len()

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.791)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.85      0.95      0.90      1128
           1       0.80      0.52      0.63       401

    accuracy                           0.84      1529
   macro avg       0.82      0.74      0.76      1529
weighted avg       0.84      0.84      0.83      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1075      53
True 1     192     209

AUC: 0.791

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:11<00:00, 16.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 613.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 599.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 578.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 613.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 588.25it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.09it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 549.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack: 100%|██████████| 200/200 [00:33<00:00,  5.99it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 220.55it/s]

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.922)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.94      0.99      0.96      1217
           1       0.97      0.73      0.83       312

    accuracy                           0.94      1529
   macro avg       0.95      0.86      0.90      1529
weighted avg       0.94      0.94      0.94      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1209       8
True 1      84     228

AUC: 0.922

=== All results and summaries saved successfully ===

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.787)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.84      0.96      0.90      1116
           1       0.83      0.52      0.64       413

    accuracy                           0.84      1529
   macro avg       0.84      0.74      0.77      1529
weighted avg       0.84      0.84      0.83      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1073      43
True 1     198     215

AUC: 0.787

=== All results and summaries saved successfully ===
[SVM] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.1: TypeError: object of type 'float' has no len()

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.662)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.74      0.96      0.84      1040
           1       0.78      0.28      0.41       489

    accuracy                           0.74      1529
   macro avg       0.76      0.62      0.62      1529
weighted avg       0.75      0.74      0.70      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1001      39
True 1     353     136

AUC: 0.662

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:11<00:00, 17.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations:  62%|██████▏   | 124/200 [00:00<00:00, 604.33it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 554.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 557.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 523.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 557.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 517.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 522.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.89it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 523.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.38it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 524.03it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 523.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 521.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 546.69it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 524.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 498.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 513.37it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 563.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.97it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 503.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 525.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 517.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 509.74it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 519.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 525.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 524.24it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 517.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 533.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 536.36it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 543.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.73it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.78it/s]
Boundary attack: 100%|██████████| 200/200 [01:12<00:00,  2.77it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 228.89it/s]

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.922)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.94      0.99      0.96      1217
           1       0.97      0.73      0.83       312

    accuracy                           0.94      1529
   macro avg       0.95      0.86      0.90      1529
weighted avg       0.94      0.94      0.94      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1209       8
True 1      84     228

AUC: 0.922

=== All results and summaries saved successfully ===

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.668)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.74      0.93      0.82      1035
           1       0.68      0.32      0.43       494

    accuracy                           0.73      1529
   macro avg       0.71      0.62      0.63      1529
weighted avg       0.72      0.73      0.70      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0     961      74
True 1     338     156

AUC: 0.668

=== All results and summaries saved successfully ===
[SVM] Detect/Retrain skipped for detector=LOSS_FILTER, rate=0.2: TypeError: object of type 'float' has no len()

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.922)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.94      0.99      0.96      1217
           1       0.97      0.73      0.83       312

    accuracy                           0.94      1529
   macro avg       0.95      0.86      0.90      1529
weighted avg       0.94      0.94      0.94      1529


Confusion Matrix:
         Pred 0  Pred 1
True 0    1209       8
True 1      84     228

AUC: 0.922

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:11<00:00, 17.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.63it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 601.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 593.01it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 593.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.75it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.38it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 581.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.73it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 588.83it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 571.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 552.21it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 521.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack: 100%|██████████| 200/200 [00:38<00:00,  5.24it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 224.26it/s]
HopSkipJump: 100%|██████████| 500/500 [00:16<00:00, 29.60it/s]

[SVM] adv-train round 0 -> 1: +500 using HSJ, train size=2198

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.929)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.93      0.98      0.96      1575
           1       0.91      0.71      0.80       404

    accuracy                           0.93      1979
   macro avg       0.92      0.85      0.88      1979
weighted avg       0.93      0.93      0.92      1979


Confusion Matrix:
         Pred 0  Pred 1
True 0    1547      28
True 1     116     288

AUC: 0.929

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:10<00:00, 18.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 601.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.47it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 563.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 593.82it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 578.90it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 595.04it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 614.61it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 616.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 537.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 568.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 552.25it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.80it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 611.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 534.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 578.40it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 557.23it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.13it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 514.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 539.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 524.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 536.99it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 573.20it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.11it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 535.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.12it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.78it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.64it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 557.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.92it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 499.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 598.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 515.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack: 100%|██████████| 200/200 [01:10<00:00,  2.82it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 221.71it/s]
HopSkipJump: 100%|██████████| 500/500 [00:15<00:00, 31.86it/s]

[SVM] adv-train round 1 -> 2: +500 using HSJ, train size=2698

Saved last run results to Results/SVMResults\results_svm.csv
Saved ROC data to Results/SVMResults\roc_svm_clean.csv (AUC = 0.949)
Saved summary (AUC + Confusion Matrix) to Results/SVMResults\svm_summary.csv

=== SVM Test Set Report ===
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      1940
           1       0.96      0.72      0.82       489

    accuracy                           0.94      2429
   macro avg       0.95      0.86      0.89      2429
weighted avg       0.94      0.94      0.93      2429


Confusion Matrix:
         Pred 0  Pred 1
True 0    1926      14
True 1     136     353

AUC: 0.949

=== All results and summaries saved successfully ===

HopSkipJump: 100%|██████████| 200/200 [00:10<00:00, 18.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 585.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.41it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 596.10it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.54it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 601.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 612.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 431.57it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 622.49it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 607.35it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 594.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 626.39it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 641.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 634.94it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 653.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 632.08it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 642.50it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 618.34it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 549.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 548.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.87it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 605.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 580.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 592.93it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 562.07it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 507.77it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 521.72it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.52it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 507.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.86it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 552.16it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 528.62it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 542.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 561.29it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.81it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 547.45it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 530.02it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 576.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.17it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 531.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 600.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.76it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.58it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 541.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 524.27it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 550.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 516.32it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 540.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 591.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.67it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 508.44it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 538.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 569.28it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 565.88it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 584.26it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 563.30it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 563.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.48it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 557.00it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 544.14it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 575.84it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 553.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 555.05it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 572.55it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 579.18it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 488.42it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 574.19it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 564.46it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 532.85it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 545.95it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 559.71it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 567.66it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 551.98it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 570.91it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 582.56it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.59it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 556.60it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 577.51it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 566.06it/s]
Boundary attack - iterations: 100%|██████████| 200/200 [00:00<00:00, 588.06it/s]
Boundary attack: 100%|██████████| 200/200 [01:03<00:00,  3.15it/s]
ZOO: 100%|██████████| 200/200 [00:00<00:00, 230.47it/s]

,model,phase,attack_type,attack,round,clean_test_acc,clean_acc_evalsubset,adv_acc_evalsubset,acc_drop_evalsubset,attack_success_rate,train_poison_rate,train_adv_augmented,eval_attack_samples,poison_meta
0,LogReg,baseline,evasion,HSJ,0,0.931765,0.930,0.070,0.860,1.000000,0.00,0,200,NaN
1,LogReg,baseline,evasion,Boundary,0,0.931765,0.930,0.380,0.550,0.650538,0.00,0,200,NaN
2,LogReg,baseline,evasion,ZOO,0,0.931765,0.930,0.315,0.615,0.661290,0.00,0,200,NaN
3,LogReg,poisoned,poison+evasion,LabelFlip(0.05) + HSJ,0,0.912941,0.880,0.120,0.760,1.000000,0.05,0,200,"{""flip_rate"": 0.05, ""num_flipped"": 85}"
4,LogReg,poisoned,poison+evasion,LabelFlip(0.05) + Boundary,0,0.912941,0.880,0.130,0.750,0.988636,0.05,0,200,"{""flip_rate"": 0.05, ""num_flipped"": 85}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,SVM,advtrain,evasion,Boundary,1,0.920000,0.930,0.075,0.855,0.994624,0.00,500,200,NaN
80,SVM,advtrain,evasion,ZOO,1,0.920000,0.930,0.330,0.600,0.645161,0.00,500,200,NaN
81,SVM,advtrain,evasion,HSJ,2,0.912941,0.895,0.195,0.700,0.888268,0.00,1000,200,NaN
82,SVM,advtrain,evasion,Boundary,2,0.912941,0.895,0.195,0.700,0.888268,0.00,1000,200,NaN
83,SVM,advtrain,evasion,ZOO,2,0.912941,0.895,0.325,0.570,0.636872,0.00,1000,200,NaN

In [59]:
# ===== Save results and quick pivots =====

out_csv = os.path.join(WORK_DIR, "standardized_results.csv")
results_df.to_csv(out_csv, index=False)
print("Saved:", out_csv)

# Quick pivot: baseline evasion drops
pivot = results_df[results_df["phase"].isin(["baseline", "advtrain"])].pivot_table(
    index=["model", "phase", "round"],
    columns=["attack"],
    values=["clean_test_acc", "adv_acc_evalsubset", "acc_drop_evalsubset"],
    aggfunc="mean"
)
pivot

Saved: StandardizedRuns\standardized_results.csv

                            acc_drop_evalsubset                \
attack                                 Boundary    HSJ    ZOO
model        phase    round
LogReg       advtrain 0                   0.545  0.830  0.620
                      1                   0.900  0.900  0.620
                      2                   0.740  0.825  0.655
             baseline 0                   0.550  0.860  0.615
NeuralNet    advtrain 0                     NaN  0.920  0.590
                      1                     NaN  0.910  0.505
                      2                     NaN  0.760  0.465
             baseline 0                     NaN  0.920  0.595
RandomForest advtrain 0                   0.160  0.225  0.010
                      1                   0.130  0.130  0.075
                      2                   0.025  0.025  0.165
             baseline 0                   0.160  0.235  0.025
SVM          advtrain 0                   0.425  0.800  0.540
                      1                   0.855  0.860  0.600
                      2                   0.700  0.700  0.570
             baseline 0                   0.410  0.810  0.540

                            adv_acc_evalsubset               clean_test_acc  \
attack                                Boundary    HSJ    ZOO       Boundary
model        phase    round
LogReg       advtrain 0                  0.370  0.085  0.295       0.931765
                      1                  0.050  0.050  0.330       0.934118
                      2                  0.185  0.100  0.270       0.936471
             baseline 0                  0.380  0.070  0.315       0.931765
NeuralNet    advtrain 0                    NaN  0.040  0.370       0.957647
                      1                    NaN  0.045  0.450       0.955294
                      2                    NaN  0.195  0.490       0.960000
             baseline 0                    NaN  0.040  0.365       0.957647
RandomForest advtrain 0                  0.785  0.720  0.935       0.950588
                      1                  0.805  0.805  0.860       0.945882
                      2                  0.790  0.790  0.650       0.816471
             baseline 0                  0.785  0.710  0.920       0.950588
SVM          advtrain 0                  0.475  0.100  0.360       0.924706
                      1                  0.075  0.070  0.330       0.920000
                      2                  0.195  0.195  0.325       0.912941
             baseline 0                  0.495  0.095  0.365       0.924706


attack                            HSJ       ZOO
model        phase    round
LogReg       advtrain 0      0.931765  0.931765
                      1      0.934118  0.934118
                      2      0.936471  0.936471
             baseline 0      0.931765  0.931765
NeuralNet    advtrain 0      0.957647  0.957647
                      1      0.955294  0.955294
                      2      0.960000  0.960000
             baseline 0      0.957647  0.957647
RandomForest advtrain 0      0.950588  0.950588
                      1      0.945882  0.945882
                      2      0.816471  0.816471
             baseline 0      0.950588  0.950588
SVM          advtrain 0      0.924706  0.924706
                      1      0.920000  0.920000
                      2      0.912941  0.912941
             baseline 0      0.924706  0.924706